In [1]:
import av
import torch
import numpy as np
from transformers import AutoProcessor, LlavaNextVideoForConditionalGeneration
import cv2

In [2]:
# Define model ID
model_id = "llava-hf/LLaVA-NeXT-Video-7B-hf"

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Load the processor and model
model = LlavaNextVideoForConditionalGeneration.from_pretrained(
    model_id,
    device_map="auto",
    low_cpu_mem_usage=True,
    load_in_4bit=True,
    # attn_implementation="flash_attention_2",
    )

config.json: 0.00B [00:00, ?B/s]

c:\Users\bigda\anaconda3\envs\gpu-env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bigda\.cache\huggingface\hub\models--llava-hf--LLaVA-NeXT-Video-7B-hf. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.18G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [5]:
processor = AutoProcessor.from_pretrained(model_id)

processor_config.json:   0%|          | 0.00/209 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/838 [00:00<?, ?B/s]

video_preprocessor_config.json: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/741 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/43.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/552 [00:00<?, ?B/s]

In [6]:
# Function to read video frames using OpenCV
def read_video_opencv(video_path, num_frames=8):
    '''
    Decode video frames using OpenCV.
    Args:
        video_path (str): Path to the video file.
        num_frames (int): Number of frames to decode.
    Returns:
        result (np.ndarray): Array of decoded frames of shape (num_frames, height, width, 3).
    '''
    frames = []
    index = 0
    video = cv2.VideoCapture(video_path)
    fps = int(video.get(cv2.CAP_PROP_FPS))
    total_num_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    indices = np.arange(0, total_num_frames, total_num_frames / num_frames).astype(int)
    while video.isOpened():
        success, frame = video.read()
        if index in indices:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(frame)
        if success:
            index += 1
        if index >= total_num_frames:
            break

    video.release()

    if not frames:
        raise ValueError("No frames were read from the video.")

    return np.stack(frames)

In [7]:
conversation = [
    {
        "role": "user",
        "content": [
            {
                "type": "text", "text": "What is abnormal action in this video?",
            },
            {
                "type": "video"
            }
        ]
    }
]

prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)

In [8]:
# video_path = "D:/6. Datasets/Fall-Dataset/Cut/C00_010_0004-C1.mp4"
# video_path = "D:/6. Datasets/Fight-Dataset/C00_083_0003-C1.mp4"
video_path = "D:/6. Datasets/Fight-Dataset/fight-video-2.mp4"
clip = read_video_opencv(video_path, num_frames=8)

inputs = processor(text=prompt, videos=clip, padding=True, return_tensors="pt").to(device)

In [9]:
outputs = model.generate(**inputs, max_new_tokens=64, do_sample=False)
print(processor.decode(outputs[0], skip_special_tokens=True))

USER:
What is abnormal action in this video? ASSISTANT: The video shows a group of people engaging in a physical altercation, with one person lying on the ground and another person standing over them. This is an abnormal action as it is not a typical or safe way to resolve conflicts. The situation appears to be escalating and could potentially lead to serious injury.

### Run Inference on unseen abnormal videos

In [15]:
import pandas as pd
import os

In [12]:
# Read unseen videos list
df_unseen_videos = pd.read_csv('../datasets/unseen_videos_information.csv')
df_unseen_videos.head()

                      video_file_name video_type   label
0   ucaerial_actions1_Walking_0_0.mp4    walking  normal
1   ucaerial_actions1_Walking_0_1.mp4    walking  normal
2   ucaerial_actions1_Walking_0_2.mp4    walking  normal
3   ucaerial_actions1_Walking_0_3.mp4    walking  normal
4  ucaerial_actions1_Walking_12_0.mp4    walking  normal

In [20]:
df_abnormal = df_unseen_videos[df_unseen_videos['label'] == 'abnormal'].reset_index(drop=True)
df_abnormal.head()

       video_file_name video_type     label
0  bitint_box_0002.mp4    hitting  abnormal
1  bitint_box_0015.mp4    hitting  abnormal
2  bitint_box_0021.mp4    hitting  abnormal
3  bitint_box_0022.mp4    hitting  abnormal
4  bitint_box_0038.mp4    hitting  abnormal

In [21]:
df_abnormal.shape

(211, 3)

In [24]:
# Run Inference on unseen abnormal videos and Save Results to CSV
base_path = "D:/6. Datasets/SPHAR-Dataset/videos"
video_names = []
video_types = []
predicted_descriptions = []

try:
    for index, row in df_abnormal.iterrows():
        video_name = row['video_file_name']
        video_type = row['video_type']
        video_path = os.path.join(base_path, video_type, video_name)
        print(f"Processing video {index + 1}/{len(df_abnormal)}: {video_name} of type: {video_type}")

        clip = read_video_opencv(video_path, num_frames=8)

        inputs = processor(text=prompt, videos=clip, padding=True, return_tensors="pt").to(device)

        outputs = model.generate(**inputs, max_new_tokens=64, do_sample=False)
        predicted_description = processor.decode(outputs[0], skip_special_tokens=True)
        predicted_description = predicted_description.split("ASSISTANT:")[-1].strip()

        video_names.append(video_name)
        video_types.append(video_type)
        predicted_descriptions.append(predicted_description)
except Exception as e:
    print(f"Error processing video {video_name}: {e}")


df_results = pd.DataFrame({
    'video_file_name': video_names,
    'video_type': video_types,
    'predicted_description': predicted_descriptions
})

df_results.to_csv('../outputs/llava_next_video_7b_abnormal_videos_inference_results.csv', index=False)
print("Inference results saved to CSV.")

Processing video 1/211: bitint_box_0002.mp4 of type: hitting
Processing video 2/211: bitint_box_0015.mp4 of type: hitting
Processing video 3/211: bitint_box_0021.mp4 of type: hitting
Processing video 4/211: bitint_box_0022.mp4 of type: hitting
Processing video 5/211: bitint_box_0038.mp4 of type: hitting
Processing video 6/211: bitint_box_0049.mp4 of type: hitting
Processing video 7/211: bitint_push_0001.mp4 of type: hitting
Processing video 8/211: bitint_push_0003.mp4 of type: hitting
Processing video 9/211: bitint_push_0005.mp4 of type: hitting
Processing video 10/211: bitint_push_0008.mp4 of type: hitting
Processing video 11/211: bitint_push_0009.mp4 of type: hitting
Processing video 12/211: bitint_push_0014.mp4 of type: hitting
Processing video 13/211: bitint_push_0022.mp4 of type: hitting
Processing video 14/211: bitint_push_0025.mp4 of type: hitting
Processing video 15/211: bitint_push_0043.mp4 of type: hitting
Processing video 16/211: bitint_push_0044.mp4 of type: hitting
Processing video 17/211: bitint_push_0048.mp4 of type: hitting
Processing video 18/211: casia_horizontalview_p08p09_fight_a1.mp4 of type: hitting
Processing video 19/211: casia_topdownview_p01p02_fight_a1.mp4 of type: hitting
Processing video 20/211: casia_topdownview_p08p09_fight_a1.mp4 of type: hitting
Processing video 21/211: caviar_Fight_Chase - Trim.mp4 of type: hitting
Processing video 22/211: caviar_Fight_OneManDown - Trim.mp4 of type: hitting
Processing video 23/211: uccrime_Arrest006_x264 - Trim.mp4 of type: hitting
Processing video 24/211: uccrime_Arrest022_x264 - Trim.mp4 of type: hitting
Processing video 25/211: uccrime_Arrest035_x264 - Trim.mp4 of type: hitting
Processing video 26/211: uccrime_Arrest037_x264 - Trim.mp4 of type: hitting
Processing video 27/211: uccrime_Arrest043_x264 - Trim.mp4 of type: hitting
Processing video 28/211: uccrime_Fighting019_x264 - Trim.mp4 of type: hitting
Processing video 29/211: uccrime_Fighting021_x264 - Trim.mp4 of type: hitting
Processing video 30/211: uccrime_Fighting028_x264 - Trim.mp4 of type: hitting
Processing video 31/211: uccrime_Fighting031_x264 - Trim.mp4 of type: hitting
Processing video 32/211: uccrime_Fighting042_x264.mp4 of type: hitting
Processing video 33/211: uccrime_Fighting049_x264 - Trim.mp4 of type: hitting
Processing video 34/211: utint_10_12_punch.mp4 of type: hitting
Processing video 35/211: utint_23_4_push.mp4 of type: hitting
Processing video 36/211: utint_25_5_punch.mp4 of type: hitting
Processing video 37/211: utint_29_5_push.mp4 of type: hitting
Processing video 38/211: utint_40_17_punch.mp4 of type: hitting
Processing video 39/211: utint_44_8_punch.mp4 of type: hitting
Processing video 40/211: utint_46_18_push.mp4 of type: hitting
Processing video 41/211: utint_55_10_punch.mp4 of type: hitting
Processing video 42/211: utint_5_1_push.mp4 of type: hitting
Processing video 43/211: utint_7_2_push.mp4 of type: hitting
Processing video 44/211: utint_8_12_push.mp4 of type: hitting
Processing video 45/211: bitint_kick_0002.mp4 of type: kicking
Processing video 46/211: bitint_kick_0003.mp4 of type: kicking
Processing video 47/211: bitint_kick_0018.mp4 of type: kicking
Processing video 48/211: bitint_kick_0026.mp4 of type: kicking
Processing video 49/211: bitint_kick_0027.mp4 of type: kicking
Processing video 50/211: bitint_kick_0029.mp4 of type: kicking
Processing video 51/211: bitint_kick_0035.mp4 of type: kicking
Processing video 52/211: bitint_kick_0043.mp4 of type: kicking
Processing video 53/211: uccrime_Assault007_x264 - Trim.mp4 of type: kicking
Processing video 54/211: uccrime_Assault008_x264 - Trim.mp4 of type: kicking
Processing video 55/211: uccrime_Assault017_x264 - Trim.mp4 of type: kicking
Processing video 56/211: uccrime_Assault030_x264.mp4 of type: kicking
Processing video 57/211: uccrime_Assault033_x264 - Trim.mp4 of type: kicking
Processing video 58/211: uccrime_Assault042_x264 - Trim.mp4 of type: kicking
Processing video 59/211: uccrime_Assault047_x264 - Trim.mp4 of type: kicking
Processing video 60/211: uccrime_Assault049_x264 - Trim.mp4 of type: kicking
Processing video 61/211: utint_13_13_kick.mp4 of type: kicking
Processing video 62/211: utint_23_14_kick.mp4 of type: kicking
Processing video 63/211: utint_27_15_kick.mp4 of type: kicking
Processing video 64/211: utint_38_7_kick.mp4 of type: kicking
Processing video 65/211: utint_50_9_kick.mp4 of type: kicking
Processing video 66/211: utint_59_10_kick.mp4 of type: kicking
Processing video 67/211: utint_9_2_kick.mp4 of type: kicking
Processing video 68/211: casia_angleview_p02_faint_a1.mp4 of type: falling
Processing video 69/211: casia_angleview_p08_faint_a1.mp4 of type: falling
Processing video 70/211: casia_horizontalview_p08_faint_a1.mp4 of type: falling
Processing video 71/211: casia_horizontalview_p19_faint_a1.mp4 of type: falling
Processing video 72/211: casia_horizontalview_p22_faint_a1.mp4 of type: falling
Processing video 73/211: casia_topdownview_p01_faint_a1.mp4 of type: falling
Processing video 74/211: casia_topdownview_p16_faint_a1.mp4 of type: falling
Processing video 75/211: caviar_Rest_WiggleOnFloor.mp4 of type: falling
Processing video 76/211: okutama_1.2.2_Lying_28.mp4 of type: falling
Processing video 77/211: okutama_1.2.6_Lying_0.mp4 of type: falling
Processing video 78/211: okutama_2.1.2_Lying_48.mp4 of type: falling
Processing video 79/211: okutama_2.1.2_Lying_49.mp4 of type: falling
Processing video 80/211: okutama_2.1.4_Lying_10.mp4 of type: falling
Processing video 81/211: okutama_2.2.10_Lying_27.mp4 of type: falling
Processing video 82/211: okutama_2.2.10_Lying_4.mp4 of type: falling
Processing video 83/211: okutama_2.2.2_Lying_1.mp4 of type: falling
Processing video 84/211: casia_horizontalview_p09_car_a1_trimmed.mp4 of type: vandalizing
Processing video 85/211: casia_topdownview_p02_car_a1_trimmed.mp4 of type: vandalizing
Processing video 86/211: uccrime_Vandalism001_x264_trimmed.mp4 of type: vandalizing
Processing video 87/211: uccrime_Vandalism006_x264_trimmed.mp4 of type: vandalizing
Processing video 88/211: uccrime_Vandalism008_x264_trimmed.mp4 of type: vandalizing
Processing video 89/211: uccrime_Vandalism010_x264_trimmed.mp4 of type: vandalizing
Processing video 90/211: uccrime_Vandalism016_x264_trimmed.mp4 of type: vandalizing
Processing video 91/211: uccrime_Vandalism026_x264_trimmed.mp4 of type: vandalizing
Processing video 92/211: uccrime_Vandalism030_x264_trimmed.mp4 of type: vandalizing
Processing video 93/211: uccrime_Vandalism038_x264_trimmed.mp4 of type: vandalizing
Processing video 94/211: uccrime_Vandalism040_x264_trimmed.mp4 of type: vandalizing
Processing video 95/211: uccrime_Vandalism050_x264_trimmed.mp4 of type: vandalizing
Processing video 96/211: casia_angleview_p04_bend_a2.mp4 of type: panicking
Processing video 97/211: casia_angleview_p06_bend_a1.mp4 of type: panicking
Processing video 98/211: casia_angleview_p08_bend_a1.mp4 of type: panicking
Processing video 99/211: casia_horizontalview_p02_bend_a1.mp4 of type: panicking
Processing video 100/211: casia_horizontalview_p03_bend_a1.mp4 of type: panicking
Processing video 101/211: casia_horizontalview_p04_bend_a1.mp4 of type: panicking
Processing video 102/211: casia_horizontalview_p07_bend_a1.mp4 of type: panicking
Processing video 103/211: casia_topdownview_p04_bend_a1.mp4 of type: panicking
Processing video 104/211: casia_topdownview_p06_bend_a1.mp4 of type: panicking
Processing video 105/211: livevid_panic2 - Trim.mp4 of type: panicking
Processing video 106/211: casia_angleview_p03p10_rob_a1.mp4 of type: stealing
Processing video 107/211: livevid_robbery4 - Trim.mp4 of type: stealing
Processing video 108/211: uccrime_Burglary009_x264 - Trim.mp4 of type: stealing
Processing video 109/211: uccrime_Burglary010_x264 - Trim.mp4 of type: stealing
Processing video 110/211: uccrime_Burglary025_x264 - Trim.mp4 of type: stealing
Processing video 111/211: uccrime_Burglary034_x264 - Trim.mp4 of type: stealing
Processing video 112/211: uccrime_Burglary039_x264 - Trim.mp4 of type: stealing
Processing video 113/211: uccrime_Burglary040_x264 - Trim.mp4 of type: stealing
Processing video 114/211: uccrime_Burglary041_x264.mp4 of type: stealing
Processing video 115/211: uccrime_Burglary043_x264.mp4 of type: stealing
Processing video 116/211: uccrime_Burglary044_x264 - Trim.mp4 of type: stealing
Processing video 117/211: uccrime_Burglary045_x264 - Trim (2).mp4 of type: stealing
Processing video 118/211: uccrime_Burglary048_x264 - Trim.mp4 of type: stealing
Processing video 119/211: uccrime_Burglary062_x264.mp4 of type: stealing
Processing video 120/211: uccrime_Burglary071_x264 - Trim.mp4 of type: stealing
Processing video 121/211: uccrime_Burglary078_x264.mp4 of type: stealing
Processing video 122/211: uccrime_Burglary079_x264.mp4 of type: stealing
Processing video 123/211: uccrime_Burglary084_x264.mp4 of type: stealing
Processing video 124/211: uccrime_Burglary092_x264.mp4 of type: stealing
Processing video 125/211: uccrime_Burglary095_x264.mp4 of type: stealing
Processing video 126/211: uccrime_Burglary099_x264.mp4 of type: stealing
Processing video 127/211: uccrime_Burglary100_x264.mp4 of type: stealing
Processing video 128/211: uccrime_Robbery016_x264.mp4 of type: stealing
Processing video 129/211: uccrime_Robbery025_x264.mp4 of type: stealing
Processing video 130/211: uccrime_Robbery029_x264.mp4 of type: stealing
Processing video 131/211: uccrime_Robbery048_x264_trimmed.mp4 of type: stealing
Processing video 132/211: uccrime_Robbery050_x264_trimmed.mp4 of type: stealing
Processing video 133/211: uccrime_Robbery059_x264_trimmed.mp4 of type: stealing
Processing video 134/211: uccrime_Robbery060_x264_trimmed.mp4 of type: stealing
Processing video 135/211: uccrime_Robbery065_x264_trimmed.mp4 of type: stealing
Processing video 136/211: uccrime_Robbery068_x264_trimmed.mp4 of type: stealing
Processing video 137/211: uccrime_Robbery073_x264_trimmed.mp4 of type: stealing
Processing video 138/211: uccrime_Robbery086_x264_trimmed.mp4 of type: stealing
Processing video 139/211: uccrime_Robbery087_x264_trimmed.mp4 of type: stealing
Processing video 140/211: uccrime_Robbery088_x264_trimmed.mp4 of type: stealing
Processing video 141/211: uccrime_Robbery089_x264_trimmed.mp4 of type: stealing
Processing video 142/211: uccrime_Robbery090_x264_trimmed.mp4 of type: stealing
Processing video 143/211: uccrime_Robbery100_x264_trimmed.mp4 of type: stealing
Processing video 144/211: uccrime_Robbery104_x264_trimmed.mp4 of type: stealing
Processing video 145/211: uccrime_Robbery111_x264_trimmed.mp4 of type: stealing
Processing video 146/211: uccrime_Robbery113_x264_trimmed.mp4 of type: stealing
Processing video 147/211: uccrime_Robbery116_x264_trimmed.mp4 of type: stealing
Processing video 148/211: uccrime_Robbery134_x264_trimmed.mp4 of type: stealing
Processing video 149/211: uccrime_Robbery140_x264_trimmed.mp4 of type: stealing
Processing video 150/211: uccrime_Robbery142_x264_trimmed.mp4 of type: stealing
Processing video 151/211: uccrime_Robbery150_x264_trimmed.mp4 of type: stealing
Processing video 152/211: uccrime_Shoplifting001_x264_trimmed.mp4 of type: stealing
Processing video 153/211: uccrime_Shoplifting007_x264_trimmed.mp4 of type: stealing
Processing video 154/211: uccrime_Shoplifting009_x264_trimmed.mp4 of type: stealing
Processing video 155/211: uccrime_Shoplifting014_x264_trimmed.mp4 of type: stealing
Processing video 156/211: uccrime_Shoplifting015_x264_trimmed.mp4 of type: stealing
Processing video 157/211: uccrime_Shoplifting020_x264_trimmed.mp4 of type: stealing
Processing video 158/211: uccrime_Shoplifting021_x264_trimmed.mp4 of type: stealing
Processing video 159/211: uccrime_Shoplifting025_x264_trimmed.mp4 of type: stealing
Processing video 160/211: uccrime_Shoplifting028_x264_trimmed.mp4 of type: stealing
Processing video 161/211: uccrime_Shoplifting047_x264_trimmed.mp4 of type: stealing
Processing video 162/211: uccrime_Shoplifting049_x264_trimmed.mp4 of type: stealing
Processing video 163/211: uccrime_Stealing003_x264_trimmed.mp4 of type: stealing
Processing video 164/211: uccrime_Stealing007_x264_trimmed.mp4 of type: stealing
Processing video 165/211: uccrime_Stealing009_x264_trimmed.mp4 of type: stealing
Processing video 166/211: uccrime_Stealing010_x264_trimmed.mp4 of type: stealing
Processing video 167/211: uccrime_Stealing014_x264_trimmed.mp4 of type: stealing
Processing video 168/211: uccrime_Stealing016_x264_trimmed.mp4 of type: stealing
Processing video 169/211: uccrime_Stealing020_x264_trimmed.mp4 of type: stealing
Processing video 170/211: uccrime_Stealing029_x264_trimmed.mp4 of type: stealing
Processing video 171/211: uccrime_Stealing031_x264_trimmed.mp4 of type: stealing
Processing video 172/211: uccrime_Stealing046_x264_trimmed.mp4 of type: stealing
Processing video 173/211: uccrime_Stealing050_x264_trimmed.mp4 of type: stealing
Processing video 174/211: uccrime_Stealing051_x264_trimmed.mp4 of type: stealing
Processing video 175/211: uccrime_Stealing052_x264_trimmed.mp4 of type: stealing
Processing video 176/211: uccrime_Stealing055_x264_trimmed.mp4 of type: stealing
Processing video 177/211: uccrime_Stealing068_x264_trimmed.mp4 of type: stealing
Processing video 178/211: uccrime_Stealing072_x264_trimmed.mp4 of type: stealing
Processing video 179/211: uccrime_Stealing075_x264_trimmed.mp4 of type: stealing
Processing video 180/211: uccrime_Stealing077_x264_trimmed.mp4 of type: stealing
Processing video 181/211: uccrime_Stealing082_x264_trimmed.mp4 of type: stealing
Processing video 182/211: uccrime_Stealing097_x264_trimmed.mp4 of type: stealing
Processing video 183/211: uccrime_Stealing105_x264_trimmed.mp4 of type: stealing
Processing video 184/211: uccrime_Stealing108_x264_trimmed.mp4 of type: stealing
Processing video 185/211: uccrime_Stealing112_x264_trimmed.mp4 of type: stealing
Processing video 186/211: uccrime_Stealing114_x264_trimmed.mp4 of type: stealing
Processing video 187/211: uccrime_Shooting009_x264 - Trim.mp4 of type: murdering
Processing video 188/211: uccrime_Shooting012_x264 - Trim.mp4 of type: murdering
Processing video 189/211: uccrime_Shooting019_x264 - Trim.mp4 of type: murdering
Processing video 190/211: uccrime_Shooting025_x264 - Trim.mp4 of type: murdering
Processing video 191/211: uccrime_Shooting028_x264.mp4 of type: murdering
Processing video 192/211: uccrime_Shooting030_x264 - Trim.mp4 of type: murdering
Processing video 193/211: uccrime_Shooting039_x264 - Trim.mp4 of type: murdering
Processing video 194/211: uccrime_Shooting053_x264 - Trim.mp4 of type: murdering
Processing video 195/211: uccrime_Arson001_x264 - Trim.mp4 of type: igniting
Processing video 196/211: uccrime_Arson002_x264 - Trim.mp4 of type: igniting
Processing video 197/211: uccrime_Arson016_x264 - Trim.mp4 of type: igniting
Processing video 198/211: uccrime_Arson023_x264 - Trim.mp4 of type: igniting
Processing video 199/211: uccrime_Arson024_x264 - Trim.mp4 of type: igniting
Processing video 200/211: uccrime_Arson027_x264 - Trim.mp4 of type: igniting
Processing video 201/211: uccrime_Arson035_x264 - Trim.mp4 of type: igniting
Processing video 202/211: uccrime_Arson044_x264 - Trim.mp4 of type: igniting
Processing video 203/211: uccrime_Explosion009_x264.mp4 of type: igniting
Processing video 204/211: uccrime_Explosion013_x264 - Trim.mp4 of type: igniting
Processing video 205/211: uccrime_Explosion023_x264 - Trim.mp4 of type: igniting
Processing video 206/211: uccrime_Explosion026_x264 - Trim.mp4 of type: igniting
Processing video 207/211: uccrime_Explosion029_x264 - Trim.mp4 of type: igniting
Processing video 208/211: uccrime_Explosion038_x264 - Trim.mp4 of type: igniting
Processing video 209/211: uccrime_Explosion039_x264 - Trim.mp4 of type: igniting
Processing video 210/211: uccrime_Explosion042_x264 - Trim.mp4 of type: igniting
Processing video 211/211: uccrime_Explosion046_x264 - Trim.mp4 of type: igniting
Inference results saved to CSV.